//
//  UIColor+YBKAdditions.swift
//
//  Generated by Zeplin on 5/25/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
    class func defaultBlueColor() ->UIColor{
        return UIColor(red: 0, green: 122/255, blue: 255/255, alpha: 1)
    }
    class func mrDarkSlateBlue() -> UIColor {
        return UIColor(red: 14 / 255 , green: 53 / 255, blue: 64 / 255 , alpha: 1.0)
    }
    class func mrLightBlueColor() -> UIColor {
        return UIColor(red: 99 / 255 , green: 215 / 255, blue: 246 / 255 , alpha: 1.0)
    }
    
    class func mrPineGreen50() -> UIColor {
        return UIColor(red: 4 / 255 , green: 20 / 255, blue: 25 / 255 , alpha: 0.5)
    }
    
	class func mrSandBrownColor() -> UIColor {
		return UIColor(red: 211.0 / 255.0, green: 150.0 / 255.0, blue: 104.0 / 255.0, alpha: 1.0)
	}

	class func mrBrownishColor() -> UIColor {
		return UIColor(red: 160.0 / 255.0, green: 98.0 / 255.0, blue: 90.0 / 255.0, alpha: 1.0)
	}

	class func mrBarneyColor() -> UIColor {
		return UIColor(red: 201.0 / 255.0, green: 28.0 / 255.0, blue: 187.0 / 255.0, alpha: 1.0)
	}

	class func mrDarkSalmonColor() -> UIColor {
		return UIColor(red: 204.0 / 255.0, green: 113.0 / 255.0, blue: 93.0 / 255.0, alpha: 1.0)
	}

	class func mrPaleColor() -> UIColor {
		return UIColor(red: 255.0 / 255.0, green: 239.0 / 255.0, blue: 214.0 / 255.0, alpha: 1.0)
	}

	class func mrDarkSandColor() -> UIColor {
		return UIColor(red: 166.0 / 255.0, green: 145.0 / 255.0, blue: 84.0 / 255.0, alpha: 1.0)
	}

	class func mrCharcoalGreyColor() -> UIColor {
		return UIColor(red: 61.0 / 255.0, green: 52.0 / 255.0, blue: 66.0 / 255.0, alpha: 1.0)
	}

	class func mrPinkishGreyColor() -> UIColor {
		return UIColor(white: 204.0 / 255.0, alpha: 1.0)
	}

	class func mrPaleGoldColor() -> UIColor {
		return UIColor(red: 251.0 / 255.0, green: 197.0 / 255.0, blue: 111.0 / 255.0, alpha: 1.0)
	}

	class func mrDenimBlueColor() -> UIColor {
		return UIColor(red: 59.0 / 255.0, green: 89.0 / 255.0, blue: 152.0 / 255.0, alpha: 1.0)
	}

	class func mrPaleTwoColor() -> UIColor {
		return UIColor(red: 254.0 / 255.0, green: 241.0 / 255.0, blue: 220.0 / 255.0, alpha: 1.0)
	}

	class func mrRedColor() -> UIColor {
		return UIColor(red: 230.0 / 255.0, green: 12.0 / 255.0, blue: 12.0 / 255.0, alpha: 1.0)
	}
    
    class func mrTurquoiseBlue() -> UIColor {
        return UIColor(red: 0 / 255.0, green: 156.0 / 255.0, blue: 197.0 / 255.0, alpha: 1.0)
    }
    
    class func mrBrightSkyBlue() -> UIColor {
        return UIColor(red: 0 / 255.0, green: 190.0 / 255.0, blue: 240.0 / 255.0, alpha: 1.0)
    }


	class func mrSeafoamBlueColor() -> UIColor {
		return UIColor(red: 110.0 / 255.0, green: 184.0 / 255.0, blue: 204.0 / 255.0, alpha: 1.0)
	}

	class func mrBubblegumColor() -> UIColor {
		return UIColor(red: 255.0 / 255.0, green: 108.0 / 255.0, blue: 197.0 / 255.0, alpha: 1.0)
	}

	class func mrRobinsEggBlueColor() -> UIColor {
		return UIColor(red: 147.0 / 255.0, green: 225.0 / 255.0, blue: 246.0 / 255.0, alpha: 1.0)
	}

	class func mrDarkSlateBlueColor() -> UIColor {
		return UIColor(red: 14.0 / 255.0, green: 53.0 / 255.0, blue: 64.0 / 255.0, alpha: 1.0)
	}

	class func mrWhite50Color() -> UIColor {
		return UIColor(white: 255.0 / 255.0, alpha: 0.5)
	}

	class func mrBlack25Color() -> UIColor {
		return UIColor(white: 0.0, alpha: 0.25)
	}

	class func mrBlack15Color() -> UIColor {
		return UIColor(white: 0.0, alpha: 0.15)
	}

	class func mrLightblueColor() -> UIColor {
		return UIColor(red: 99.0 / 255.0, green: 215.0 / 255.0, blue: 246.0 / 255.0, alpha: 1.0)
	}

	class func mrBlack20Color() -> UIColor {
		return UIColor(white: 0.0, alpha: 0.2)
	}

	class func mrRobinsEggBlue0Color() -> UIColor {
		return UIColor(red: 146.0 / 255.0, green: 225.0 / 255.0, blue: 246.0 / 255.0, alpha: 0.0)
	}

	class func mrWaterBlueColor() -> UIColor {
		return UIColor(red: 11.0 / 255.0, green: 151.0 / 255.0, blue: 189.0 / 255.0, alpha: 1.0)
	}

	class func mrWhiteColor() -> UIColor {
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	class func mrBlack60Color() -> UIColor {
		return UIColor(white: 0.0, alpha: 0.6)
	}

	class func mrBlack40Color() -> UIColor {
		return UIColor(white: 0.0, alpha: 0.4)
	}
}
