# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Mr-Ride' do
pod 'PureLayout'
pod 'SideMenu'
pod 'Charts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Alamofire'
pod 'Fabric'
pod 'Crashlytics'
pod 'Amplitude-iOS'

end

